//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationDetail
    {
        public int Id { get; set; }
        public Nullable<int> PreferredSlot { get; set; }
        public int RegistrationId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual Course Course { get; set; }
    }
}
