//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseMark
    {
        public int Id { get; set; }
        public Nullable<double> Mark { get; set; }
        public int CourseMarkId { get; set; }
        public string Note { get; set; }
        public int StudentInCourseId { get; set; }
    
        public virtual CourseMark CourseMark { get; set; }
        public virtual StudentInCourse StudentInCourse { get; set; }
    }
}
