//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectMark
    {
        public int Id { get; set; }
        public string ComponentName { get; set; }
        public double Percentage { get; set; }
        public int SubjectId { get; set; }
        public Nullable<System.DateTime> EffectivenessDate { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
