//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<bool> IsIncreaseTransaction { get; set; }
        public Nullable<int> Status { get; set; }
        public string Notes { get; set; }
        public string UserName { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
